config/routes.rb
AppFinder::Application.routes.draw do
  
  resources :apps do
  end
  

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :developer, :icon_url, :like_count, :long_description, :ratings, :screenshot_url, :short_discription, :title, :video_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :icon_url %><br />
    <%= f.text_field :icon_url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :developer %><br />
    <%= f.text_field :developer %>
  </div>
  <div class="field">
    <%= f.label :ratings %><br />
    <%= f.text_field :ratings %>
  </div>
  <div class="field">
    <%= f.label :screenshot_url %><br />
    <%= f.text_field :screenshot_url %>
  </div>
  <div class="field">
    <%= f.label :short_discription %><br />
    <%= f.text_field :short_discription %>
  </div>
  <div class="field">
    <%= f.label :long_description %><br />
    <%= f.text_field :long_description %>
  </div>
  <div class="field">
    <%= f.label :like_count %><br />
    <%= f.number_field :like_count %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br />
    <%= f.text_field :video_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Icon url:</b>
  <%= @app.icon_url %>
</p>

<p>
  <b>Title:</b>
  <%= @app.title %>
</p>

<p>
  <b>Developer:</b>
  <%= @app.developer %>
</p>

<p>
  <b>Ratings:</b>
  <%= @app.ratings %>
</p>

<p>
  <b>Screenshot url:</b>
  <%= @app.screenshot_url %>
</p>

<p>
  <b>Short discription:</b>
  <%= @app.short_discription %>
</p>

<p>
  <b>Long description:</b>
  <%= @app.long_description %>
</p>

<p>
  <b>Like count:</b>
  <%= @app.like_count %>
</p>

<p>
  <b>Video url:</b>
  <%= @app.video_url %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AppFinder</title>
  <link rel="stylesheet" href="assets/bootstrap.min.css">
    <link rel="stylesheet" href="assets/bootstrap-responsive.min.css">
    <link rel="stylesheet" href="assets/mosaic.css">
    <link rel="stylesheet" href="assets/tinybox.css">
    <link rel="stylesheet" href="assets/chosen.css" />
    <link rel="stylesheet" href="assets/jquery-ui-min.css" />    
    <link rel="stylesheet" href="assets/application.css">
    <link rel="stylesheet" href="assets/responsiveSlides.css">
    <link rel="stylesheet" href="assets/flexSlider.css">
    <script src="http://www.youtube.com/iframe_api" type="text/javascript"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
<header class="navbar navbar-fixed-top">
        	<div id="site-header-inner" class="navbar-inner">
	        	<div class="container">      
		        	<div id="logo" class="brand">
		        		<img src="/assets/img/logo.png" alt="Tappollo" >
		        	</div><!--/#logo -->

	        		<ul id="main-nav" class="nav">
		        		<li class="main-nav-item active">
		        			<a href="/">
		        				Apps
		        			</a>
		        		</li><!--/li -->
		        		<li class="main-nav-item">
		        			<a href="/developers">
		        				Developers
		        			</a>
		        		</li><!--/li -->
	        		</ul><!--/#main-nav -->
	        		
					<form id="main-search" class="navbar-search pull-right">
						<i class="icon-search"></i>
					  <input type="text" id="main-search-query" class="search-query" placeholder="Search">
					</form><!--/#main-search -->
						
						
	        		<ul id="profile" class="nav pull-right">
		        		<li class="profile-item">
		        			<a href="#register">
		        				register
		        			</a>
		        		</li><!--/li -->
		        		<li class="profile-item">
		        			<a href="#login">
		        				login
		        			</a>
		        		</li><!--/li -->
	        		</ul><!--/#profile -->

	        	
	        	</div><!--/.container -->
	        	
        	</div><!--/.navbar-inner -->
        </header><!--/header -->
        
        <div id="stage" class = "clearfix" >
        	<!--  login view -->
        	<div id="login-view" class="stage-view">
        	</div>
        	
        	<div id="developers-view" class="stage-view">
        	</div>
        	
        	<!-- register view -->
        	<div id="register-view" class="stage-view"> </div>
        	
        	<div id="detail-view" class="stage-view">
        		<div class="pageLoading"></div>
        	</div>
        	<div id="app-view" class="stage-view active">
        	</div><!-- /#app-view -->
        </div> <!-- /stage -->

        <footer>
                <p>&copy; Company 2012</p>
        </footer>
		<div id="loadingContainer"></div>
        
<script type="text/javascript">
  $(function() {
	window.router = new AppFinder.Routers.WaterfallAppsRouter();
	window.router.start();    
  });
  
	$(document).on("click", "a[href^='/']", function(event) {
	  if (!event.altKey && !event.ctrlKey && !event.metaKey && !event.shiftKey) {
	    event.preventDefault();
	    var url = $(event.currentTarget).attr("href").replace(/^\//, "");
	    window.router.navigate(url, { trigger: true });
	  }
	});
</script>
</body>
</html>